"""Mask PNG helpers and candidate-combine operations.

These utilities are intentionally small and dependency-free for local mock
testing. They handle the unfiltered RGB/gray PNGs generated by the mock mask
provider.
"""

from __future__ import annotations

from pathlib import Path
import struct
import zlib


class MaskImageError(ValueError):
    """Raised when a mask image cannot be read or combined."""


def write_mask_png(path: Path, width: int, height: int, pixels: list[bool]) -> None:
    if width < 1 or height < 1:
        raise MaskImageError("mask dimensions must be positive")
    if len(pixels) != width * height:
        raise MaskImageError("mask pixel count does not match dimensions")

    path.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for y in range(height):
        row = bytearray([0])
        for x in range(width):
            value = 255 if pixels[y * width + x] else 0
            row.extend([value, value, value])
        rows.append(bytes(row))

    raw = b"".join(rows)
    png = b"".join(
        [
            b"\x89PNG\r\n\x1a\n",
            _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)),
            _png_chunk(b"IDAT", zlib.compress(raw)),
            _png_chunk(b"IEND", b""),
        ]
    )
    path.write_bytes(png)


def read_mask_png(path: Path) -> tuple[int, int, list[bool]]:
    data = path.read_bytes()
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        raise MaskImageError(f"not a PNG mask: {path}")

    offset = 8
    width = 0
    height = 0
    color_type = -1
    idat = b""
    while offset < len(data):
        length = struct.unpack(">I", data[offset : offset + 4])[0]
        chunk_type = data[offset + 4 : offset + 8]
        chunk_data = data[offset + 8 : offset + 8 + length]
        offset += 12 + length
        if chunk_type == b"IHDR":
            width, height, bit_depth, color_type, compression, filter_method, interlace = struct.unpack(">IIBBBBB", chunk_data)
            if bit_depth != 8 or compression != 0 or filter_method != 0 or interlace != 0:
                raise MaskImageError("unsupported PNG mask format")
        elif chunk_type == b"IDAT":
            idat += chunk_data
        elif chunk_type == b"IEND":
            break

    if width < 1 or height < 1:
        raise MaskImageError("PNG mask is missing IHDR")

    raw = zlib.decompress(idat)
    pixels: list[bool] = []
    if color_type == 2:
        stride = width * 3
        for y in range(height):
            start = y * (stride + 1)
            if raw[start] != 0:
                raise MaskImageError("unsupported PNG filter in mask")
            row = raw[start + 1 : start + 1 + stride]
            for x in range(width):
                pixels.append(row[x * 3] > 127)
    elif color_type == 0:
        stride = width
        for y in range(height):
            start = y * (stride + 1)
            if raw[start] != 0:
                raise MaskImageError("unsupported PNG filter in mask")
            row = raw[start + 1 : start + 1 + stride]
            pixels.extend(value > 127 for value in row)
    else:
        raise MaskImageError("unsupported PNG color type for mask")

    return width, height, pixels


def combine_mask_files(paths: list[Path], operation: str) -> tuple[int, int, list[bool]]:
    if not paths:
        raise MaskImageError("at least one candidate mask is required")

    loaded = [read_mask_png(path) for path in paths]
    width, height, first_pixels = loaded[0]
    for other_width, other_height, _pixels in loaded[1:]:
        if other_width != width or other_height != height:
            raise MaskImageError("candidate mask dimensions do not match")

    operation = operation.lower()
    if operation in {"replace", "union"}:
        result = [False] * (width * height)
        for _w, _h, pixels in loaded:
            result = [current or incoming for current, incoming in zip(result, pixels)]
    elif operation == "intersect":
        result = first_pixels[:]
        for _w, _h, pixels in loaded[1:]:
            result = [current and incoming for current, incoming in zip(result, pixels)]
    elif operation == "subtract":
        result = first_pixels[:]
        for _w, _h, pixels in loaded[1:]:
            result = [current and not incoming for current, incoming in zip(result, pixels)]
    else:
        raise MaskImageError(f"unsupported mask operation: {operation}")

    return width, height, result


def rectangle_mask(width: int, height: int, x: int, y: int, rect_width: int, rect_height: int) -> list[bool]:
    pixels = [False] * (width * height)
    max_x = min(width, x + rect_width)
    max_y = min(height, y + rect_height)
    for row in range(max(0, y), max_y):
        for col in range(max(0, x), max_x):
            pixels[row * width + col] = True
    return pixels


def mask_bbox_area(width: int, height: int, pixels: list[bool]) -> tuple[list[int], int]:
    coords = [(idx % width, idx // width) for idx, active in enumerate(pixels) if active]
    if not coords:
        return [0, 0, 0, 0], 0
    min_x = min(x for x, _y in coords)
    max_x = max(x for x, _y in coords)
    min_y = min(y for _x, y in coords)
    max_y = max(y for _x, y in coords)
    return [min_x, min_y, max_x - min_x + 1, max_y - min_y + 1], len(coords)


def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    crc = zlib.crc32(chunk_type + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", crc)
