"""ComfyUI reference provider.

Workflow JSON is read from server-side configuration. Dynamic values can be
inserted either with placeholders such as {prompt} or explicit field_mappings.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from uuid import uuid4
from typing import Any

from .base import ReferenceGenerationRequest, ReferenceGenerationResult, ReferenceProviderError
from .config import ReferenceProviderConfig, load_reference_provider_config
from .custom_http_provider import CustomHTTPReferenceProvider
from .template import render_template, set_path


class ComfyUIReferenceProvider(CustomHTTPReferenceProvider):
    name = "comfyui"

    def __init__(self, config: ReferenceProviderConfig | None = None) -> None:
        self.config = config or load_reference_provider_config(self.name)

    def generate(self, request: ReferenceGenerationRequest, job_dir: Path) -> ReferenceGenerationResult:
        if not self.config.endpoint:
            raise ReferenceProviderError(400, "comfyui endpoint is not configured")
        if not self.config.workflow_path:
            raise ReferenceProviderError(400, "comfyui workflow_path is not configured")

        workflow = self._load_workflow()
        workflow = render_template(workflow, request, self.config.model)
        self._apply_field_mappings(workflow, request)

        payload = {
            "prompt": workflow,
            "client_id": str(uuid4()),
        }
        if request.extra.get("comfyui_extra_data"):
            payload["extra_data"] = request.extra["comfyui_extra_data"]

        body, content_type = self._post_json(self.config.endpoint, payload)
        image_bytes, suffix, metadata = self._extract_image(body, content_type)
        output_name = f"reference{suffix}"
        (job_dir / output_name).write_bytes(image_bytes)
        return ReferenceGenerationResult(
            provider=self.name,
            status="done",
            output_path=output_name,
            message="Reference generated by ComfyUI",
            metadata=metadata,
        )

    def _load_workflow(self) -> Any:
        path = Path(self.config.workflow_path)
        if not path.is_file():
            raise ReferenceProviderError(400, f"comfyui workflow_path does not exist: {path}")
        return json.loads(path.read_text(encoding="utf-8"))

    def _apply_field_mappings(self, workflow: Any, request: ReferenceGenerationRequest) -> None:
        values = {
            "prompt": request.prompt,
            "negative_prompt": request.negative_prompt,
            "seed": request.seed,
            "width": request.width,
            "height": request.height,
            "strength": request.strength,
            "model": self.config.model,
        }
        for key, value in request.input_images.items():
            values[f"input_images.{key}"] = value
        for source_key, target_path in self.config.field_mappings.items():
            if source_key in values:
                set_path(workflow, target_path, copy.deepcopy(values[source_key]))
