"""Configurable HTTP reference provider.

This adapter is intentionally generic: endpoint, model, headers, request body,
and response extraction all come from server-side configuration.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path
import urllib.error
import urllib.request
from typing import Any

from .base import ReferenceGenerationRequest, ReferenceGenerationResult, ReferenceProviderError
from .config import ReferenceProviderConfig, load_reference_provider_config
from .template import get_path, json_dumps_bytes, render_template


class CustomHTTPReferenceProvider:
    name = "custom_http"

    def __init__(self, config: ReferenceProviderConfig | None = None) -> None:
        self.config = config or load_reference_provider_config(self.name)

    def generate(self, request: ReferenceGenerationRequest, job_dir: Path) -> ReferenceGenerationResult:
        if not self.config.endpoint:
            raise ReferenceProviderError(400, f"{self.name} endpoint is not configured")

        payload = self._build_payload(request)
        body, content_type = self._post_json(self.config.endpoint, payload)
        image_bytes, suffix, metadata = self._extract_image(body, content_type)
        output_name = f"reference{suffix}"
        (job_dir / output_name).write_bytes(image_bytes)
        return ReferenceGenerationResult(
            provider=self.name,
            status="done",
            output_path=output_name,
            message=f"Reference generated by {self.name}",
            metadata=metadata,
        )

    def _build_payload(self, request: ReferenceGenerationRequest) -> Any:
        if self.config.request_template:
            return render_template(self.config.request_template, request, self.config.model)
        return {
            "model": self.config.model,
            "prompt": request.prompt,
            "negative_prompt": request.negative_prompt,
            "seed": request.seed,
            "width": request.width,
            "height": request.height,
            "strength": request.strength,
            "input_images": request.input_images,
            "extra": request.extra,
        }

    def _post_json(self, endpoint: str, payload: Any) -> tuple[bytes, str]:
        headers = {"Content-Type": "application/json", **self.config.headers}
        request = urllib.request.Request(
            endpoint,
            data=json_dumps_bytes(payload),
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.config.timeout) as response:
                content_type = response.headers.get("Content-Type", "")
                return response.read(), content_type
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise ReferenceProviderError(502, f"{self.name} HTTP error {exc.code}: {detail}") from exc
        except urllib.error.URLError as exc:
            raise ReferenceProviderError(502, f"{self.name} request failed: {exc}") from exc

    def _extract_image(self, body: bytes, content_type: str) -> tuple[bytes, str, dict[str, Any]]:
        if content_type.lower().startswith("image/"):
            return body, _suffix_from_content_type(content_type), {"content_type": content_type}

        try:
            response_json = json.loads(body.decode("utf-8"))
        except json.JSONDecodeError as exc:
            raise ReferenceProviderError(502, f"{self.name} response is neither image nor JSON") from exc

        mapping = self.config.response_mapping
        if "image_base64" in mapping:
            return _decode_base64_image(get_path(response_json, mapping["image_base64"])), ".png", {"response_mapping": "image_base64"}
        if "image_url" in mapping:
            return _download_image(str(get_path(response_json, mapping["image_url"])), self.config.timeout)
        if "image_path" in mapping:
            image_path = Path(str(get_path(response_json, mapping["image_path"])))
            if not image_path.is_file():
                raise ReferenceProviderError(502, f"mapped image_path does not exist: {image_path}")
            return image_path.read_bytes(), image_path.suffix or ".png", {"response_mapping": "image_path"}

        for fallback_key in ("image_base64", "b64_json", "image"):
            value = response_json.get(fallback_key) if isinstance(response_json, dict) else None
            if isinstance(value, str):
                return _decode_base64_image(value), ".png", {"response_mapping": fallback_key}

        raise ReferenceProviderError(502, f"{self.name} response_mapping did not locate an image")


def _decode_base64_image(value: Any) -> bytes:
    if not isinstance(value, str) or not value:
        raise ReferenceProviderError(502, "mapped image_base64 is empty")
    if "," in value and value.strip().lower().startswith("data:"):
        value = value.split(",", 1)[1]
    return base64.b64decode(value)


def _download_image(url: str, timeout: float) -> tuple[bytes, str, dict[str, Any]]:
    request = urllib.request.Request(url, method="GET")
    with urllib.request.urlopen(request, timeout=timeout) as response:
        content_type = response.headers.get("Content-Type", "")
        return response.read(), _suffix_from_content_type(content_type or url), {"response_mapping": "image_url", "image_url": url}


def _suffix_from_content_type(value: str) -> str:
    lower = value.lower()
    if "jpeg" in lower or lower.endswith(".jpg") or lower.endswith(".jpeg"):
        return ".jpg"
    if "png" in lower or lower.endswith(".png"):
        return ".png"
    return ".png"
